version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  # Start from the default set (errcheck, govet, ineffassign, staticcheck, unused)
  default: standard

  # Extra linters on top of the default set, chosen from your `help linters` output.
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
    - whitespace

  # Turn off ones that are often too noisy / heavy; keep this as needed.
  disable:
    - cyclop
    - funlen
    - gocyclo

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/apartmentlines/mattermost-poor-mans-scheduled-messages

issues:
  exclude-rules:
    - path: server/configuration.go
      linters:
        - unused
    - path: _test\.go
      linters:
        - bodyclose
    - linters:
        - revive
      text: unused-parameter
