// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports (interfaces: BotService)
//
// Generated by this command:
//
//	mockgen -destination=../../adapters/mock/bot_mock.go -package=mock github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports BotService
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/mattermost/mattermost/server/public/model"
	pluginapi "github.com/mattermost/mattermost/server/public/pluginapi"
	gomock "go.uber.org/mock/gomock"
)

// MockBotService is a mock of BotService interface.
type MockBotService struct {
	ctrl     *gomock.Controller
	recorder *MockBotServiceMockRecorder
	isgomock struct{}
}

// MockBotServiceMockRecorder is the mock recorder for MockBotService.
type MockBotServiceMockRecorder struct {
	mock *MockBotService
}

// NewMockBotService creates a new mock instance.
func NewMockBotService(ctrl *gomock.Controller) *MockBotService {
	mock := &MockBotService{ctrl: ctrl}
	mock.recorder = &MockBotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotService) EXPECT() *MockBotServiceMockRecorder {
	return m.recorder
}

// EnsureBot mocks base method.
func (m *MockBotService) EnsureBot(bot *model.Bot, profileImagePath ...pluginapi.EnsureBotOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{bot}
	for _, a := range profileImagePath {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnsureBot", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureBot indicates an expected call of EnsureBot.
func (mr *MockBotServiceMockRecorder) EnsureBot(bot any, profileImagePath ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{bot}, profileImagePath...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBot", reflect.TypeOf((*MockBotService)(nil).EnsureBot), varargs...)
}
