// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports (interfaces: ChannelService)
//
// Generated by this command:
//
//	mockgen -destination=../../adapters/mock/channel_mock.go -package=mock github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports ChannelService
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	ports "github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelService is a mock of ChannelService interface.
type MockChannelService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelServiceMockRecorder
	isgomock struct{}
}

// MockChannelServiceMockRecorder is the mock recorder for MockChannelService.
type MockChannelServiceMockRecorder struct {
	mock *MockChannelService
}

// NewMockChannelService creates a new mock instance.
func NewMockChannelService(ctrl *gomock.Controller) *MockChannelService {
	mock := &MockChannelService{ctrl: ctrl}
	mock.recorder = &MockChannelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelService) EXPECT() *MockChannelServiceMockRecorder {
	return m.recorder
}

// GetInfoOrUnknown mocks base method.
func (m *MockChannelService) GetInfoOrUnknown(channelID string) *ports.ChannelInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfoOrUnknown", channelID)
	ret0, _ := ret[0].(*ports.ChannelInfo)
	return ret0
}

// GetInfoOrUnknown indicates an expected call of GetInfoOrUnknown.
func (mr *MockChannelServiceMockRecorder) GetInfoOrUnknown(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfoOrUnknown", reflect.TypeOf((*MockChannelService)(nil).GetInfoOrUnknown), channelID)
}

// MakeChannelLink mocks base method.
func (m *MockChannelService) MakeChannelLink(info *ports.ChannelInfo) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeChannelLink", info)
	ret0, _ := ret[0].(string)
	return ret0
}

// MakeChannelLink indicates an expected call of MakeChannelLink.
func (mr *MockChannelServiceMockRecorder) MakeChannelLink(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeChannelLink", reflect.TypeOf((*MockChannelService)(nil).MakeChannelLink), info)
}
