// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports (interfaces: ListService)
//
// Generated by this command:
//
//	mockgen -destination=../../adapters/mock/list_service_mock.go -package=mock github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports ListService
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/mattermost/mattermost/server/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockListService is a mock of ListService interface.
type MockListService struct {
	ctrl     *gomock.Controller
	recorder *MockListServiceMockRecorder
	isgomock struct{}
}

// MockListServiceMockRecorder is the mock recorder for MockListService.
type MockListServiceMockRecorder struct {
	mock *MockListService
}

// NewMockListService creates a new mock instance.
func NewMockListService(ctrl *gomock.Controller) *MockListService {
	mock := &MockListService{ctrl: ctrl}
	mock.recorder = &MockListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListService) EXPECT() *MockListServiceMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockListService) Build(userID string) *model.CommandResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", userID)
	ret0, _ := ret[0].(*model.CommandResponse)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockListServiceMockRecorder) Build(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockListService)(nil).Build), userID)
}
