// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports (interfaces: PostService)
//
// Generated by this command:
//
//	mockgen -destination=../../adapters/mock/post_mock.go -package=mock github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports PostService
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/mattermost/mattermost/server/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
	isgomock struct{}
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(post *model.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", post)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), post)
}

// DM mocks base method.
func (m *MockPostService) DM(botID, userID string, post *model.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DM", botID, userID, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// DM indicates an expected call of DM.
func (mr *MockPostServiceMockRecorder) DM(botID, userID, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DM", reflect.TypeOf((*MockPostService)(nil).DM), botID, userID, post)
}

// SendEphemeralPost mocks base method.
func (m *MockPostService) SendEphemeralPost(userID string, post *model.Post) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEphemeralPost", userID, post)
}

// SendEphemeralPost indicates an expected call of SendEphemeralPost.
func (mr *MockPostServiceMockRecorder) SendEphemeralPost(userID, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEphemeralPost", reflect.TypeOf((*MockPostService)(nil).SendEphemeralPost), userID, post)
}

// UpdateEphemeralPost mocks base method.
func (m *MockPostService) UpdateEphemeralPost(userID string, post *model.Post) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateEphemeralPost", userID, post)
}

// UpdateEphemeralPost indicates an expected call of UpdateEphemeralPost.
func (mr *MockPostServiceMockRecorder) UpdateEphemeralPost(userID, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEphemeralPost", reflect.TypeOf((*MockPostService)(nil).UpdateEphemeralPost), userID, post)
}
