// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports (interfaces: SlashCommandService)
//
// Generated by this command:
//
//	mockgen -destination=../../adapters/mock/slash_mock.go -package=mock github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports SlashCommandService
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/mattermost/mattermost/server/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSlashCommandService is a mock of SlashCommandService interface.
type MockSlashCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockSlashCommandServiceMockRecorder
	isgomock struct{}
}

// MockSlashCommandServiceMockRecorder is the mock recorder for MockSlashCommandService.
type MockSlashCommandServiceMockRecorder struct {
	mock *MockSlashCommandService
}

// NewMockSlashCommandService creates a new mock instance.
func NewMockSlashCommandService(ctrl *gomock.Controller) *MockSlashCommandService {
	mock := &MockSlashCommandService{ctrl: ctrl}
	mock.recorder = &MockSlashCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlashCommandService) EXPECT() *MockSlashCommandServiceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockSlashCommandService) Register(cmd *model.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockSlashCommandServiceMockRecorder) Register(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSlashCommandService)(nil).Register), cmd)
}
