// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=../../adapters/mock/store_mock.go -package=mock github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/internal/ports Store
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	types "github.com/apartmentlines/mattermost-plugin-poor-mans-scheduled-messages/server/types"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CleanupMessageFromUserIndex mocks base method.
func (m *MockStore) CleanupMessageFromUserIndex(userID, msgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupMessageFromUserIndex", userID, msgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupMessageFromUserIndex indicates an expected call of CleanupMessageFromUserIndex.
func (mr *MockStoreMockRecorder) CleanupMessageFromUserIndex(userID, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupMessageFromUserIndex", reflect.TypeOf((*MockStore)(nil).CleanupMessageFromUserIndex), userID, msgID)
}

// DeleteScheduledMessage mocks base method.
func (m *MockStore) DeleteScheduledMessage(userID, msgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScheduledMessage", userID, msgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScheduledMessage indicates an expected call of DeleteScheduledMessage.
func (mr *MockStoreMockRecorder) DeleteScheduledMessage(userID, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScheduledMessage", reflect.TypeOf((*MockStore)(nil).DeleteScheduledMessage), userID, msgID)
}

// GenerateMessageID mocks base method.
func (m *MockStore) GenerateMessageID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMessageID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateMessageID indicates an expected call of GenerateMessageID.
func (mr *MockStoreMockRecorder) GenerateMessageID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMessageID", reflect.TypeOf((*MockStore)(nil).GenerateMessageID))
}

// GetScheduledMessage mocks base method.
func (m *MockStore) GetScheduledMessage(msgID string) (*types.ScheduledMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledMessage", msgID)
	ret0, _ := ret[0].(*types.ScheduledMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledMessage indicates an expected call of GetScheduledMessage.
func (mr *MockStoreMockRecorder) GetScheduledMessage(msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledMessage", reflect.TypeOf((*MockStore)(nil).GetScheduledMessage), msgID)
}

// ListScheduledMessages mocks base method.
func (m *MockStore) ListScheduledMessages() ([]*types.ScheduledMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduledMessages")
	ret0, _ := ret[0].([]*types.ScheduledMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduledMessages indicates an expected call of ListScheduledMessages.
func (mr *MockStoreMockRecorder) ListScheduledMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduledMessages", reflect.TypeOf((*MockStore)(nil).ListScheduledMessages))
}

// ListUserMessageIDs mocks base method.
func (m *MockStore) ListUserMessageIDs(userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserMessageIDs", userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserMessageIDs indicates an expected call of ListUserMessageIDs.
func (mr *MockStoreMockRecorder) ListUserMessageIDs(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserMessageIDs", reflect.TypeOf((*MockStore)(nil).ListUserMessageIDs), userID)
}

// SaveScheduledMessage mocks base method.
func (m *MockStore) SaveScheduledMessage(userID string, msg *types.ScheduledMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveScheduledMessage", userID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveScheduledMessage indicates an expected call of SaveScheduledMessage.
func (mr *MockStoreMockRecorder) SaveScheduledMessage(userID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveScheduledMessage", reflect.TypeOf((*MockStore)(nil).SaveScheduledMessage), userID, msg)
}
